[pytest]
DJANGO_SETTINGS_MODULE = tests.settings
python_files = test_*.py
python_classes = Test*
python_functions = test_*
pythonpath = .
addopts = 
    --strict-markers
    --strict-config
    --cov=django_role_based_masking
    --cov-report=term-missing
    --cov-report=html
testpaths = tests
